<?php

namespace Modules\Warehouse\Repositories\Eloquent;

use Modules\Warehouse\Repositories\IssueCardRepository;
use Modules\Core\Repositories\Eloquent\EloquentBaseRepository;

class EloquentIssueCardRepository extends EloquentBaseRepository implements IssueCardRepository
{
	/**
     * Defien columns for Datatable
     * @return array
     */
    public function getCollumns($warehouse = null,$frontend = false)
    {
        $settings = null;
        if (is_object($warehouse)) {
            $settings = $warehouse->settings;
        }
        if(is_array($warehouse)){
            $settings = $warehouse;
        }
        
        $collumns = [
        'id' => [
            'name' => 'id',
            'data' => 'id',
            'title' => trans('warehouse::issuecards.table.id'),
            'searchable' => false,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::issuecards.table.id'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'exported' => [
            'name' => 'exported',
            'data' => 'exported',
            'title' => trans('warehouse::issuecards.table.exported'),
            'searchable' => false,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::issuecards.table.exported'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'material_number'=> [
            'name' => 'material_number',
            'data' => 'material_number',
            'title' => trans('warehouse::items.table.material_number'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.material_number'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'name'=> [
            'name' => 'name',
            'data' => 'name',
            'title' => trans('warehouse::items.table.name'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.name'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'user_full_name'=> [
            'name' => 'user_full_name',
            'data' => 'user_full_name',
            'title' => trans('warehouse::issuecards.form.user_full_name'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::issuecards.form.user_full_name'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'local_name'=> [
            'name' => 'translations.local_name',
            'data' => 'local_name',
            'title' => trans('warehouse::items.table.local_name'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.local_name'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'costcenter_id'=> [
            'name' => 'costcenter_id',
            'data' => 'costcenter_id',
            'title' => trans('warehouse::costcenters.title.costcenters'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::costcenters.title.costcenters'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'machinepart_id'=> [
            'name' => 'machinepart_id',
            'data' => 'machinepart_id',
            'title' => trans('warehouse::machineparts.title.machineparts'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::machineparts.title.machineparts'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'quantity'=> [
            'name' => 'quantity',
            'data' => 'quantity',
            'title' => trans('warehouse::issuecards.table.quantity'),
            'searchable' => false,
            'orderable' => false,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::issuecards.table.quantity'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'status'=> [
            'name' => 'status',
            'data' => 'status',
            'title' => trans('warehouse::issuecards.table.itemstatus'),
            'searchable' => false,
            'orderable' => false,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::issuecards.table.itemstatus'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'issuing_volume'=> [
            'name' => 'issuing_volume',
            'data' => 'issuing_volume',
            'title' => trans('warehouse::issuecards.table.issuing_volume'),
            'searchable' => false,
            'orderable' => false,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::issuecards.table.quantity'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'minimum'=> [
            'name' => 'minimum',
            'data' => 'minimum',
            'title' => trans('warehouse::items.table.minimum'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.minimum'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'maximum'=> [
            'name' => 'maximum',
            'data' => 'maximum',
            'title' => trans('warehouse::items.table.maximum'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.maximum'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'specification'=> [
            'name' => 'specification',
            'data' => 'specification',
            'title' => trans('warehouse::items.table.specification'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.specification'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'order_number'=> [
            'name' => 'order_number',
            'data' => 'order_number',
            'title' => trans('warehouse::items.table.order_number'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.order_number'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'price'=> [
            'name' => 'price',
            'data' => 'price',
            'title' => trans('warehouse::items.table.price'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.price'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'manufacture'=> [
            'name' => 'manufacture',
            'data' => 'manufacture',
            'title' => trans('warehouse::items.table.manufacture'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.manufacture'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'supplier'=> [
            'name' => 'supplier',
            'data' => 'supplier',
            'title' => trans('warehouse::items.table.supplier'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.supplier'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'suppliers'=> [
            'name' => 'suppliers',
            'data' => 'suppliers',
            'title' => trans('warehouse::items.table.suppliers'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.suppliers'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'documentation_number'=> [
            'name' => 'documentation_number',
            'data' => 'documentation_number',
            'title' => trans('warehouse::items.table.documentation_number'),
            'searchable' => true,
            'orderable' => true,
            // 'render' => 'function(){}',
            'footer' => trans('warehouse::items.table.documentation_number'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'url'=> [
            'name' => 'url',
            'data' => 'url',
            'title' => trans('warehouse::items.table.url'),
            'searchable' => false,
            'orderable' => false,
            'footer' => trans('warehouse::items.table.url'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'created_at'=> [
            'name' => 'created_at',
            'data' => 'created_at',
            'title' => trans('warehouse::issuecards.table.created_at'),
            'searchable' => true,
            'orderable' => true,
            'footer' => trans('warehouse::issuecards.table.created_at'),
            'exportable' => true,
            'printable' => true,
            'visible' => true,
            ],
        'action'=> [
            'defaultContent' => '',
            'data'           => 'action',
            'name'           => 'action',
            'title'          => trans('warehouse::issuecards.table.action'),
            'render'         => null,
            'orderable'      => false,
            'searchable'     => false,
            'exportable'     => false,
            'printable'      => true,
            'footer'         => trans('warehouse::issuecards.table.action'),
            ],
        ];
        if (is_object($settings)) {
            if ($frontend && $settings->issuecard_guest_disabled_fields) {
                return array_only($collumns,$settings->issuecard_guest_disabled_fields);
            }
            return array_only($collumns,$settings->issuecard_disabled_fields);
        }
        if(is_array($settings)){
            return array_only($collumns,$settings);
        }
        return $collumns;
    }
}
